[tanks]
class = "heavy_tank"
description = "Tanks"
labels = [
  "type_99",     # Heavy Main Battle Tank
  "t80b",        # Heavy Main Battle Tank
  "m2002",       # Heavy Main Battle Tank
  "oplot_m",     # Heavy Main Battle Tank
  "al_khalid",   # mbt heavy
  "vickers_mk3", # mbt medium
  "chieftain",   # mbt medium
  "t55",         # Soviet medium 

  "sabalan",
  "type_62",
  "t64e",
  "t80u",
  "magach_7",
  "pt91_twardy",
  "vickers_mk7",
  "t72b4",
  "ruag_leopard_upgrade",

  "k21_with_xc8",
  "leopard_c2",
  "m551_sheridan",
  "tank_ex",
  "tam",
  "m1a2_abrams",
  "tm_800",
  "t95",
  "m84ab1",
  "t90",
  "t12_black_eagle",
  "merkava_mk4",
  "arjun_mk2",
  "k2_black_panther_mbt",
  "type_90_II",
  "t84",
  "btmp_84",
  "bmpt_72",
  "leopard",
  "t80",
  "bmt_72",
  "merkava_mk2",
  "t62",
  "t80ud",
  "super_m48",
  "m8_buford",
  "t72m2_moderna",
  "zulfiqar_3",
  "kaplan",
  "t80bvm",
  "osorio",
  "chieftain_untold_story",
  "leopard_2a4m_can",
  "type_63a",
  "arjun",
  "challenger_1",
  "sprut_sdm1",
  "ariete",
  "type_80",
  "mbt_3000",
  "expeditionary_tank",
  "oplot",
  "m1a1_abrams",
  "karrar",
  "zulfiqar_2",
  "mb3_tamoyo",
  "leopard_2a7",
  "m1_abrams",
  "cv90120t",
  "type_99g",
  "anders",
  "vickers_mk4",
  "merkava_mk3",
  "sk105_kurassier",
  "t80um1_bars",
  "type_96",
  "m1a2_sep",
  "type_74",
  "vfm_5",
  "merkava_mk4_meil_ruach",
  "sprut_sd",
  "pl_01",
  "t72ua1",
  "t90ms_tagil",
  "t64b1m",
  "armata",
  "t64bm_bulat",
  "m60_patton",
  "zbd_2000_light_tank",
  "mars_15",
  "leclerc",
  "revolution",
]

[lavs]
class = "lavs"
description = "Light armored vehicles"
labels = [
  "k21_105", # South Korean infantry fighting vehicle and is not a tank

  "sabra",
  "t55_enigma",
  "vt5",
  "of_40",
  "fv101_scorpion",
  "amx_40",
  "k1a1",
  "amx_30",
  "tosan",
  "pt76",
  "gl5",
  "m60a2",
  "pt_16",
  "t90m",
  "altay",
  "m60a3",
  "type_90",
  "m1985",
  "tk_x",
  "vt2",
  "m84",
  "amx_13",
  "m90_vihor",
  "type_98",
  "bmpt",
  "merkava_mk1",
  "leopard_2ng",
  "leopard_2a6",
  "t72",
  "t72b3",
  "tr85m1",
  "amx_32",
  "leopard_2pl",
  "marder_light_tank",
  "nkpz",
  "type_63",
  "t64",
  "ikv_91",
  "unidentified_north_korean_mbt",
]

[unknown_military]
class = "unknown_military"
description = "Unknown Combat Vehicles"
labels = [
  "lince",
  "tank_technology_demonstrator",
  "super_m60",
  "olifant_mk2",
  "zulfiqar_1",
  "challenger_2",
  "t72m4",
  "m95_degman",
  "cv90105",
  "drozd",
  "st2",
  "jaguar",
  "tusk",
  "t84_yatagan",
  "k1",
  "leopard_2a5",
  "leopard_2",
  "vt4",
  "ztq_15",
  "m60_phoenix",
  "olifant_mk1b",
]
